AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: "Create a AWS CodePipeline to Operationalize a Machine Learning Model."

Resources:
  CommonStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: common.yaml

  PipelineStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: pipeline.yaml
      Parameters:
        ImageRepoName: !GetAtt CommonStack.Outputs.ContainerRegistryName
        ModelSourceRepo: !GetAtt CommonStack.Outputs.MLOpsRepoName
        MLOpsBucket: !GetAtt CommonStack.Outputs.MLOpsBucket

  MWAAStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mwaa-environment.yaml
      Parameters:
        ImageRepoName: !GetAtt CommonStack.Outputs.ContainerRegistryName
        MLOpsBucket: !GetAtt CommonStack.Outputs.MLOpsBucket
        DataBucket: !GetAtt CommonStack.Outputs.DataBucket
        ModelSourceRepo: !GetAtt CommonStack.Outputs.MLOpsRepoName

