version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sm-pipelines"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7k53qf17jw1d"
s3_prefix = "sm-pipelines"
region = "us-west-2"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
